### ISSUE TITLE
2016/04/15 硅谷故事：众生相

### ISSUE THREAD

**Issue by sivagao** [gaohailang/blog#20]
> 翻译自[Techies](A study of Silicon Valley)，本文作者陈述了他为什么想关注不同背景的人怎么开始从事这个行业（如年过半百高龄的，换了行业的，身有残疾的，移民的，LGBT同性恋的，没有学位的，作为父母的，通过自学的，贫穷的，作为研究员的，设计师开发者企业家，做管理的，投资人的，变性者等等）
## 硅谷故事：众生相

在今年一月份我宣布我想做一个聚焦硅谷人物的肖像项目。三个月过去了，下面是我的成果：

[www.techiesproject.com](http://www.techiesproject.com)

我开始做这个项目主要是因为如下两个原因：我希望给外界展示更为具体真实的硅谷的那些技术人的面貌。我也希望讲述这个行业中那帮默默无闻的人物的故事。

从一月份开始我开始和技术圈来自各种背景的，大概100人左右进行交流。从事这份行业对他们来说并不容易，即使现在他们也遇到各种难题。但是他们坚持下来了，因为他们天赋异禀，他们热情工作，他们迫切希望改善技术生态~

这个项目设计的初衷是让你主导怎么使用它。你可以使用过滤器来确保你来排序和探索你感兴趣的内容。也许你想借此机会看看和你工作生活背景迥异的人是怎么进去这个圈子的，或者你也可以看看和你背景相似的人的那些故事。他们和你来自于同一个地方或前行业，或者和你经历过一样的困难~

![](https://raw.githubusercontent.com/gaohailang/blog/master/source/images/14604976511056.jpg)￼

我希望感兴趣的人利用好这些内容基于它们做自己想做的东西。他们可以深入追寻，逐个击破和构建新的故事。我希望它让部分人感到不愉快，愤怒和获有灵感。我希望它能激发出更多新的，难以应对的问题，不断想要回答的尝试。

我希望大家尽自己所能分享这个项目（网站），和那些认为技术圈是一个完美的英才聚集的地方的人分享，和那些想要多元化员工，演讲者和顾问的人分享，和那些在这技术圈感到孤独的人分享。

我以我的一位受访者Victor Roman的一句话结尾：

> 我认为去思考理解人们是从哪里起步非常关键。因为很多时候我们衡量一个人是否成功却忽略了他们是从哪里开始旅程，他们是否在同一起跑线上。一些人可能在起跑线的一两公里外开始，最终没有获得第一名，人们会说『哈，他们做的不是不好』。单实际上他们比第一名跑的更快，跑的更远的路，他们只是在不一样的起点出发。所以，我觉得去思考和关注那些起跑线外的一两公里，那些具体导致不同距离的背后原因和努力。

**Comment by Kenshinhu** [comment]
弱弱问什么是 LGBT?

在 2016年4月13日 上午6:10，gaohailang notifications@github.com写道：

**Comment by sivagao** [comment]
@Kenshinhu 一定是故意的，Lesbian Gay Bisexual Transgender
