### ISSUE TITLE
tmp-markdown-angular2

### ISSUE THREAD

**Issue by sivagao** [gaohailang/blog#44]
clear~~

**Comment by rccoder** [comment]
好长好长。

![image](https://cloud.githubusercontent.com/assets/7554325/19355468/0dddd3e8-919d-11e6-884d-5f11d10f9af4.png)

问一下这种图是利用什么工具画的，看上去很萌的样子

**Comment by sivagao** [comment]
@rccoder 用 OmniGraffle 画的，有不同的画笔风格和主题~
